project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercide 1
            href: Hands-on_Ex1/Hands-onEx1.html 
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2/Hands-on_Ex2.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class Exercise/In-class Exercise 1/In-class Exercise 1.html
          - text: In-class Exercise 2
            href: In-class Exercise/In-class Exercise 2/In-class_Ex2.html
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

